id: ADE5DE4F5
base_file: fFAE6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:57:11.347427
  last_modified_at: 2022-06-19 17:57:11.347430
