id: ADE5DE4F5
base_file: f671B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:57:11.344482
  last_modified_at: 2022-06-19 17:57:11.344489
